import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-4 w-100">
        <div className="container my-3">
          <div className="jumbotron">
            <h1 className="display-4">Welcome to Keep Notes</h1>
            <p className="lead">Add your notes on this website. It is 100% completely secured.</p>
            <Link className="btn btn-primary btn-lg" href="/notes/">Your Notes</Link>
          </div>
        </div>
      </div>
    </div>
  )
}
